import xlwt
import random

"""
This file aims at generating sample student databases and attendance reports(generated by Zoom adn Teams)
"""


wb = xlwt.Workbook()
wb2 = xlwt.Workbook()
sheet1 = wb.add_sheet('Sheet 1')
sheet2 = wb2.add_sheet("Sheet 1")
list_of_names = ["A SAMEER  AHMED", "Aadi Sharma", "Abhijit Banerjee", "Ravish Kumar", "Pranav Mistry",
                 "Garima Arora", "Gagandeep Kang", "Y.C. Deveshwar", "Tulsi Sharma",
                 "Ram SIngh", "Vibhuti Shah", "Peter Parker", "Vishwajeet Anand", "Maria James",
                 "Aditi", "Harmanpreet Kaur", "Abbu Bucker", "Veeresh RG", "Vignesh BH", "Ayush Tiwari",
                 "Ayush Jain", "Manas", "Manasvi Chauhan", "Abinivesh Reddy", "Falguni Pathak", "Rajendra Sharma",
                 "Jason Lobo", "Chatur", "Mayank Gandhi", "Priyanka Singh", "Syeda Afreen", "Angel Angelica",
                 "James Harris", "Sneha Sood", "Syed Shaik", "Muskan Afreen", "Samyukta Shekar",
                 "Srinivas Srinidhi", "Nidhi Dani", "Akash Ganna", "Payal Jain", "Aryan K.G", "Ashish Arpit",
                 "Madhu Jain", "Advik", "Atharv", "Ashwin", "Rohit Tanwar", "Sumit Singh", "Sahil Jadhav",
                 "Naman", "Harsh Rai", "Sarthak Joshi", "Mukesh Modi", "Sameer Khan", "Nazia Ahmed",
                 "Kevin Arvind", "Sham Arvind", "Pankaj Tripathi", "Abhinandu", "Ali Faiz", "Md. Fouzan",
                 "Sara Singhania", "Amit Saxena", "Devika Oberoi", "Kapil", "Amita Singh", "Noor Khan",
                 "Manshi Mehta", "Naina Patel", "Khushi Sharma", "Abhishek Kumar", "Gauri Khan", "Priyesh Tiwari",
                 "Abhishek R U", "Zeeshan Zubair", "Varun Rajput", "Vedika Goenka", "Anirudha Awasthi", "Manny Paul", "Dhruvika Devanand"
                 ]


def ifsingle(a):
    if len(str(a)) == 1:
        return "0"+a
    else:
        return a


list_of_classes = ["6A", "6B", "6C", "7A", "7B", "7C", "8A", "8B", "8C", "9A",
                   "9B", "9C", "10A", "10B", "10C", "11A", "11B", "11C", "12A", "12B", "12C"]
alpha = []
for i in range(1, 1123):
    student = random.choice(list_of_names) + " " + \
        random.choice(list_of_classes)
    while student in alpha:
        student = random.choice(list_of_names) + " " + \
            random.choice(list_of_classes)
    alpha.append(student)
    sheet1.write(i, 0, student.upper())

classlist = []
c = 0
cc = 0
for i in alpha:
    c = c+1

    if "10" in i:              #creating a sample attendance report for students of class 10
        classlist.append(i)
        sheet2.write(cc, 0, i)
        sheet2.write(cc, 1, "Joined")
        sheet2.write(cc, 2, "05-01-21")
        sheet2.write(cc, 3, "10:" + ifsingle(str(random.randint(1, 26))
                                             ) + ":" + ifsingle(str(random.randint(1, 58))))
        cc = cc+1

for i in range(len(classlist)//2):
    cc = cc + 1
    a = random.choice(classlist)
    sheet2.write(cc, 0, a)
    sheet2.write(cc, 1, "Left")
    sheet2.write(cc, 2, "05-01-21")
    r = random.randint(27, 55)
    z = random.randint(1, 55)
    sheet2.write(cc, 3, "10:" + ifsingle(str(r)) + ":" + ifsingle(str(z)))
    cc = cc+1
    sheet2.write(cc, 0, a)
    sheet2.write(cc, 1, "Joined")
    sheet2.write(cc, 2, "05-01-21")
    sheet2.write(cc, 3, "10:" + ifsingle(str(r+2)) + ":" + ifsingle(str(z+2)))
wb.save('Students_Database.xls')
wb2.save("Present_List_Class10.xls")
